version: '3.7'

services:
  app:
    build: ./
    command: streamlit run app/main.py --server.port 8501
    volumes:
      - ./:/usr/src/app
    ports:
      - 8501:8501
    image: yourstreamlitapp:latest
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]